// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun zero() = 0

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst intProgression = 1 until 7
        for (i in intProgression step zero()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst longProgression = 1L until 7L
        for (i in longProgression step zero().toLong()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst charProgression = 'a' until 'g'
        for (i in charProgression step zero()) {
        }
    }

    return "OK"
}