// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun zero() = 0

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst intProgression = 7 downTo 1
        for (i in intProgression step zero()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst longProgression = 7L downTo 1L
        for (i in longProgression step zero().toLong()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst charProgression = 'g' downTo 'a'
        for (i in charProgression step zero()) {
        }
    }

    return "OK"
}