// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst intProgression = 7 downTo 1
        for (i in intProgression step -1) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst longProgression = 7L downTo 1L
        for (i in longProgression step -1L) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst charProgression = 'g' downTo 'a'
        for (i in charProgression step -1) {
        }
    }

    return "OK"
}