// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    konst intProgression = 7.toByte() downTo 1.toShort()
    for (i in intProgression step 2) {
        intList += i
    }
    assertEquals(listOf(7, 5, 3, 1), intList)

    konst longList = mutableListOf<Long>()
    konst longProgression = 7 downTo 1L
    for (i in longProgression step 2) {
        longList += i
    }
    assertEquals(listOf(7L, 5L, 3L, 1L), longList)

    return "OK"
}