// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    konst intProgression = 1 downTo 1
    for (i in intProgression step 2) {
        intList += i
    }
    assertEquals(listOf(1), intList)

    konst longList = mutableListOf<Long>()
    konst longProgression = 1L downTo 1L
    for (i in longProgression step 2L) {
        longList += i
    }
    assertEquals(listOf(1L), longList)

    konst charList = mutableListOf<Char>()
    konst charProgression = 'a' downTo 'a'
    for (i in charProgression step 2) {
        charList += i
    }
    assertEquals(listOf('a'), charList)

    return "OK"
}