// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    konst intProgression = 7 downTo 1
    for (i in intProgression step 7) {
        intList += i
    }
    assertEquals(listOf(7), intList)

    konst longList = mutableListOf<Long>()
    konst longProgression = 7L downTo 1L
    for (i in longProgression step 7L) {
        longList += i
    }
    assertEquals(listOf(7L), longList)

    konst charList = mutableListOf<Char>()
    konst charProgression = 'g' downTo 'a'
    for (i in charProgression step 7) {
        charList += i
    }
    assertEquals(listOf('g'), charList)

    return "OK"
}