// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsDceOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonToolOptions {
    override konst options: org.jetbrains.kotlin.gradle.dsl.KotlinJsDceCompilerToolOptions

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default konstue: false
     */
    var devMode: kotlin.Boolean
        get() = options.devMode.get()
        set(konstue) = options.devMode.set(konstue)

    /**
     * Output directory
     * Default konstue: null
     */
    @Deprecated(message = "Use task 'destinationDirectory' to configure output directory", level = DeprecationLevel.WARNING)
    var outputDirectory: kotlin.String?
        get() = options.outputDirectory.orNull
        set(konstue) = options.outputDirectory.set(konstue)
}
