// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsDceCompilerToolOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonCompilerToolOptions {

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Input
    konst devMode: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Output directory
     * Default konstue: null
     */
    @Deprecated(message = "Use task 'destinationDirectory' to configure output directory", level = DeprecationLevel.WARNING)
    @get:org.gradle.api.tasks.Internal
    konst outputDirectory: org.gradle.api.provider.Property<kotlin.String>
}
