// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonToolOptions {
    konst options: org.jetbrains.kotlin.gradle.dsl.KotlinCommonCompilerToolOptions

    /**
     * Report an error if there are any warnings
     * Default konstue: false
     */
    var allWarningsAsErrors: kotlin.Boolean
        get() = options.allWarningsAsErrors.get()
        set(konstue) = options.allWarningsAsErrors.set(konstue)

    /**
     * Generate no warnings
     * Default konstue: false
     */
    var suppressWarnings: kotlin.Boolean
        get() = options.suppressWarnings.get()
        set(konstue) = options.suppressWarnings.set(konstue)

    /**
     * Enable verbose logging output
     * Default konstue: false
     */
    var verbose: kotlin.Boolean
        get() = options.verbose.get()
        set(konstue) = options.verbose.set(konstue)

    /**
     * A list of additional compiler arguments
     * Default konstue: emptyList<String>()
     */
    var freeCompilerArgs: kotlin.collections.List<kotlin.String>
        get() = options.freeCompilerArgs.get()
        set(konstue) = options.freeCompilerArgs.set(konstue)
}
