// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonCompilerToolOptions {

    /**
     * Report an error if there are any warnings
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Input
    konst allWarningsAsErrors: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Generate no warnings
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Internal
    konst suppressWarnings: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Enable verbose logging output
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Internal
    konst verbose: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * A list of additional compiler arguments
     * Default konstue: emptyList<String>()
     */
    @get:org.gradle.api.tasks.Input
    konst freeCompilerArgs: org.gradle.api.provider.ListProperty<kotlin.String>
}
