// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJvmOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonOptions {
    override konst options: org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompilerOptions

    /**
     * Generate metadata for Java 1.8 reflection on method parameters
     * Default konstue: false
     */
    var javaParameters: kotlin.Boolean
        get() = options.javaParameters.get()
        set(konstue) = options.javaParameters.set(konstue)

    private konst kotlin.String?.jvmTargetCompilerOption get() = if (this != null) org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(this) else null

    private konst org.jetbrains.kotlin.gradle.dsl.JvmTarget.jvmTargetKotlinOption get() = this.target

    /**
     * Target version of the generated JVM bytecode (1.8, 9, 10, ..., 20), default is 1.8
     * Possible konstues: "1.8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"
     * Default konstue: JvmTarget.DEFAULT
     */
    var jvmTarget: kotlin.String
        get() = options.jvmTarget.get().jvmTargetKotlinOption
        set(konstue) = options.jvmTarget.set(konstue.jvmTargetCompilerOption)

    /**
     * Name of the generated .kotlin_module file
     * Default konstue: null
     */
    var moduleName: kotlin.String?
        get() = options.moduleName.orNull
        set(konstue) = options.moduleName.set(konstue)

    /**
     * Don't automatically include the Java runtime into the classpath
     * Default konstue: false
     */
    var noJdk: kotlin.Boolean
        get() = options.noJdk.get()
        set(konstue) = options.noJdk.set(konstue)
}
