// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJvmCompilerOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonCompilerOptions {

    /**
     * Generate metadata for Java 1.8 reflection on method parameters
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Input
    konst javaParameters: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Target version of the generated JVM bytecode (1.8, 9, 10, ..., 20), default is 1.8
     * Possible konstues: "1.8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"
     * Default konstue: JvmTarget.DEFAULT
     */
    @get:org.gradle.api.tasks.Input
    konst jvmTarget: org.gradle.api.provider.Property<org.jetbrains.kotlin.gradle.dsl.JvmTarget>

    /**
     * Name of the generated .kotlin_module file
     * Default konstue: null
     */
    @get:org.gradle.api.tasks.Optional
    @get:org.gradle.api.tasks.Input
    konst moduleName: org.gradle.api.provider.Property<kotlin.String>

    /**
     * Don't automatically include the Java runtime into the classpath
     * Default konstue: false
     */
    @get:org.gradle.api.tasks.Input
    konst noJdk: org.gradle.api.provider.Property<kotlin.Boolean>
}
