/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// IGNORE_BACKEND: JS
// !LANGUAGE: +JsAllowInkonstidCharsIdentifiersEscaping
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: escaped-interfaces.kt

@file:JsExport


package foo


fun `inkonstid@name sum`(x: Int, y: Int): Int =
    x + y


fun inkonstid_args_name_sum(`first konstue`: Int, `second konstue`: Int): Int =
    `first konstue` + `second konstue`

// Properties


konst `inkonstid name konst`: Int = 1

var `inkonstid@name var`: Int = 1

// Classes


class `Inkonstid A`

class A1(konst `first konstue`: Int, var `second.konstue`: Int)

class A2 {
    var `inkonstid:name`: Int = 42
}

class A3 {
    fun `inkonstid@name sum`(x: Int, y: Int): Int =
        x + y

    fun inkonstid_args_name_sum(`first konstue`: Int, `second konstue`: Int): Int =
        `first konstue` + `second konstue`
}


class A4 {
    companion object {
        var `@inkonstid+name@` = 23
        fun `^)run.something.weird^(`(): String = ")_("
    }
}