/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: enum-classes.kt

@file:JsExport

package foo


enum class TestEnumClass(konst constructorParameter: String) {
    A("aConstructorParameter"),
    B("bConstructorParameter");

    konst foo = ordinal

    fun bar(konstue: String) = konstue

    fun bay() = name

    class Nested {
        konst prop: String = "hello2"
    }
}


class OuterClass {
    enum class NestedEnum {
        A,
        B
    }
}

