/*
 * Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */
package kotlinx.cinterop

//
// NOTE: THIS FILE IS AUTO-GENERATED by the generators/nativeInteropRuntime/NativeInteropRuntimeGenerator.kt
//

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Boolean> NativePlacement.alloc(konstue: T): BooleanVarOf<T> =
        alloc<BooleanVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Byte> NativePlacement.alloc(konstue: T): ByteVarOf<T> =
        alloc<ByteVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Short> NativePlacement.alloc(konstue: T): ShortVarOf<T> =
        alloc<ShortVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Int> NativePlacement.alloc(konstue: T): IntVarOf<T> =
        alloc<IntVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Long> NativePlacement.alloc(konstue: T): LongVarOf<T> =
        alloc<LongVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : UByte> NativePlacement.alloc(konstue: T): UByteVarOf<T> =
        alloc<UByteVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : UShort> NativePlacement.alloc(konstue: T): UShortVarOf<T> =
        alloc<UShortVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : UInt> NativePlacement.alloc(konstue: T): UIntVarOf<T> =
        alloc<UIntVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : ULong> NativePlacement.alloc(konstue: T): ULongVarOf<T> =
        alloc<ULongVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Float> NativePlacement.alloc(konstue: T): FloatVarOf<T> =
        alloc<FloatVarOf<T>> { this.konstue = konstue }

/**
 * Allocates variable with given konstue type and initializes it with given konstue.
 */
@Suppress("FINAL_UPPER_BOUND")
@ExperimentalForeignApi
public fun <T : Double> NativePlacement.alloc(konstue: T): DoubleVarOf<T> =
        alloc<DoubleVarOf<T>> { this.konstue = konstue }

