/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// MODULE_KIND: ES
// FILE: esm.kt

@file:JsExport

package foo


konst konstue = 10


var variable = 10


class C(konst x: Int) {
    fun doubleX() = x * 2
}


object O {
    konst konstue = 10
}


object Parent {
    konst konstue = 10
    class Nested {
        konst konstue = 10
    }
}


fun box(): String = "OK"