// Library part (build by FE 1.0)

//package lib
//
//@Target(AnnotationTarget.PROPERTY, AnnotationTarget.FIELD)
//annotation class Property(
//    konst description: String = "",
//    konst ignore: Boolean = false,
//
//    konst externalName: String = ""
//)
//
//open class LocatableRunConfigurationOptions {
//    @Property(ignore = true)
//    konst isNameGenerated by lazy { false }
//}

// Main part

package use

import lib.LocatableRunConfigurationOptions

class JvmMainMethodRunConfigurationOptions : LocatableRunConfigurationOptions()
