// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    konst intProgression = 8 downTo 1
    for (i in (intProgression.reversed() step 2).reversed()) {
        intList += i
    }
    assertEquals(listOf(7, 5, 3, 1), intList)

    konst longList = mutableListOf<Long>()
    konst longProgression = 8L downTo 1L
    for (i in (longProgression.reversed() step 2L).reversed()) {
        longList += i
    }
    assertEquals(listOf(7L, 5L, 3L, 1L), longList)

    konst charList = mutableListOf<Char>()
    konst charProgression = 'h' downTo 'a'
    for (i in (charProgression.reversed() step 2).reversed()) {
        charList += i
    }
    assertEquals(listOf('g', 'e', 'c', 'a'), charList)

    return "OK"
}