// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    for (i in 1 downTo 1 step 2) {
        intList += i
    }
    assertEquals(listOf(1), intList)

    konst longList = mutableListOf<Long>()
    for (i in 1L downTo 1L step 2L) {
        longList += i
    }
    assertEquals(listOf(1L), longList)

    konst charList = mutableListOf<Char>()
    for (i in 'a' downTo 'a' step 2) {
        charList += i
    }
    assertEquals(listOf('a'), charList)

    return "OK"
}