// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    for (i in 7 downTo 1 step 7) {
        intList += i
    }
    assertEquals(listOf(7), intList)

    konst longList = mutableListOf<Long>()
    for (i in 7L downTo 1L step 7L) {
        longList += i
    }
    assertEquals(listOf(7L), longList)

    konst charList = mutableListOf<Char>()
    for (i in 'g' downTo 'a' step 7) {
        charList += i
    }
    assertEquals(listOf('g'), charList)

    return "OK"
}