// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst intProgression = 1..7
        for (i in intProgression step 0 step 2) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst longProgression = 1L..7L
        for (i in longProgression step 0L step 2L) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst charProgression = 'a'..'g'
        for (i in charProgression step 0 step 2) {
        }
    }

    return "OK"
}