// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    konst intProgression = 0..Int.MAX_VALUE
    for (i in intProgression step Int.MAX_VALUE) {
        intList += i
    }
    assertEquals(listOf(0, Int.MAX_VALUE), intList)

    konst longList = mutableListOf<Long>()
    konst longProgression = 0L..Long.MAX_VALUE
    for (i in longProgression step Long.MAX_VALUE) {
        longList += i
    }
    assertEquals(listOf(0L, Long.MAX_VALUE), longList)

    konst charList = mutableListOf<Char>()
    konst charProgression = 0.toChar()..Char.MAX_VALUE
    for (i in charProgression step Char.MAX_VALUE.toInt()) {
        charList += i
    }
    assertEquals(listOf(0.toChar(), Char.MAX_VALUE), charList)

    return "OK"
}