/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: deprecated.kt

@file:JsExport

package foo


@Deprecated("message 1")
fun foo() {}


@Deprecated("message 2")
konst bar: String = "Test"


@Deprecated("message 3")
class TestClass


class AnotherClass @Deprecated("message 4") constructor(konst konstue: String) {
    @JsName("fromNothing")
    @Deprecated("message 5") constructor(): this("Test")

    @JsName("fromInt")
    constructor(konstue: Int): this(konstue.toString())

    @Deprecated("message 6")
    fun foo() {}

    fun baz() {}

    @Deprecated("message 7")
    konst bar: String = "Test"
}


interface TestInterface {
    @Deprecated("message 8")
    fun foo()
    fun bar()
    @Deprecated("message 9")
    konst baz: String
}


object TestObject {
    @Deprecated("message 10")
    fun foo() {}
    fun bar() {}
    @Deprecated("message 11")
    konst baz: String = "Test"
}
