package transitiveStory.midActual.sourceCalls.intemediateInheritorCall

import transitiveStory.midActual.sourceCalls.intemediateCall.BottomActualCommonInheritor
import transitiveStory.midActual.sourceCalls.intemediateCall.BottomActualMPPInheritor

konst t123 = BottomActualCommonInheritor()
konst t122 = BottomActualMPPInheritor()