/*
 * Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.incremental;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.GenerateJsTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("js/js.translator/testData/incremental/inkonstidation")
@TestDataPath("$PROJECT_ROOT")
public class JsIrInkonstidationTestGenerated extends AbstractJsIrInkonstidationTest {
    @Test
    @TestMetadata("addUpdateRemoveDependentFile")
    public void testAddUpdateRemoveDependentFile() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/addUpdateRemoveDependentFile/");
    }

    @Test
    @TestMetadata("addUpdateRemoveDependentModule")
    public void testAddUpdateRemoveDependentModule() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/addUpdateRemoveDependentModule/");
    }

    @Test
    public void testAllFilesPresentInInkonstidation() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("js/js.translator/testData/incremental/inkonstidation"), Pattern.compile("^([^_](.+))$"), null, TargetBackend.JS_IR, false);
    }

    @Test
    @TestMetadata("circleExportsUpdate")
    public void testCircleExportsUpdate() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/circleExportsUpdate/");
    }

    @Test
    @TestMetadata("circleInlineImportsUpdate")
    public void testCircleInlineImportsUpdate() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/circleInlineImportsUpdate/");
    }

    @Test
    @TestMetadata("class")
    public void testClass() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/class/");
    }

    @Test
    @TestMetadata("classFunctionsAndFields")
    public void testClassFunctionsAndFields() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/classFunctionsAndFields/");
    }

    @Test
    @TestMetadata("companionFunction")
    public void testCompanionFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/companionFunction/");
    }

    @Test
    @TestMetadata("companionInlineFunction")
    public void testCompanionInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/companionInlineFunction/");
    }

    @Test
    @TestMetadata("companionProperties")
    public void testCompanionProperties() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/companionProperties/");
    }

    @Test
    @TestMetadata("companionWithStdLibCall")
    public void testCompanionWithStdLibCall() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/companionWithStdLibCall/");
    }

    @Test
    @TestMetadata("constVals")
    public void testConstVals() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/constVals/");
    }

    @Test
    @TestMetadata("crossModuleReferences")
    public void testCrossModuleReferences() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/crossModuleReferences/");
    }

    @Test
    @TestMetadata("eagerInitialization")
    public void testEagerInitialization() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/eagerInitialization/");
    }

    @Test
    @TestMetadata("enum")
    public void testEnum() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/enum/");
    }

    @Test
    @TestMetadata("enumsInInlineFunctions")
    public void testEnumsInInlineFunctions() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/enumsInInlineFunctions/");
    }

    @Test
    @TestMetadata("esModules")
    public void testEsModules() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/esModules/");
    }

    @Test
    @TestMetadata("exceptionsFromInlineFunction")
    public void testExceptionsFromInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/exceptionsFromInlineFunction/");
    }

    @Test
    @TestMetadata("exportsThroughInlineFunction")
    public void testExportsThroughInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/exportsThroughInlineFunction/");
    }

    @Test
    @TestMetadata("fakeOverrideClassFunctionQualifiers")
    public void testFakeOverrideClassFunctionQualifiers() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideClassFunctionQualifiers/");
    }

    @Test
    @TestMetadata("fakeOverrideInheritance")
    public void testFakeOverrideInheritance() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideInheritance/");
    }

    @Test
    @TestMetadata("fakeOverrideInlineExtension")
    public void testFakeOverrideInlineExtension() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideInlineExtension/");
    }

    @Test
    @TestMetadata("fakeOverrideInlineFunction")
    public void testFakeOverrideInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideInlineFunction/");
    }

    @Test
    @TestMetadata("fakeOverrideInlineProperty")
    public void testFakeOverrideInlineProperty() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideInlineProperty/");
    }

    @Test
    @TestMetadata("fakeOverrideInterfaceFunctionQualifiers")
    public void testFakeOverrideInterfaceFunctionQualifiers() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fakeOverrideInterfaceFunctionQualifiers/");
    }

    @Test
    @TestMetadata("fastPath1")
    public void testFastPath1() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fastPath1/");
    }

    @Test
    @TestMetadata("fastPath2")
    public void testFastPath2() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/fastPath2/");
    }

    @Test
    @TestMetadata("friendDependency")
    public void testFriendDependency() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/friendDependency/");
    }

    @Test
    @TestMetadata("functionDefaultParams")
    public void testFunctionDefaultParams() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/functionDefaultParams/");
    }

    @Test
    @TestMetadata("functionSignature")
    public void testFunctionSignature() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/functionSignature/");
    }

    @Test
    @TestMetadata("functionTypeInterface")
    public void testFunctionTypeInterface() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/functionTypeInterface/");
    }

    @Test
    @TestMetadata("functionTypeInterfaceReflect")
    public void testFunctionTypeInterfaceReflect() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/functionTypeInterfaceReflect/");
    }

    @Test
    @TestMetadata("genericFunctions")
    public void testGenericFunctions() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/genericFunctions/");
    }

    @Test
    @TestMetadata("genericInlineFunctions")
    public void testGenericInlineFunctions() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/genericInlineFunctions/");
    }

    @Test
    @TestMetadata("gettersAndSettersInlining")
    public void testGettersAndSettersInlining() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/gettersAndSettersInlining/");
    }

    @Test
    @TestMetadata("inlineBecomeNonInline")
    public void testInlineBecomeNonInline() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineBecomeNonInline/");
    }

    @Test
    @TestMetadata("inlineFunctionAnnotations")
    public void testInlineFunctionAnnotations() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionAnnotations/");
    }

    @Test
    @TestMetadata("inlineFunctionAsFunctionReference")
    public void testInlineFunctionAsFunctionReference() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionAsFunctionReference/");
    }

    @Test
    @TestMetadata("inlineFunctionAsParam")
    public void testInlineFunctionAsParam() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionAsParam/");
    }

    @Test
    @TestMetadata("inlineFunctionCircleUsage")
    public void testInlineFunctionCircleUsage() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionCircleUsage/");
    }

    @Test
    @TestMetadata("inlineFunctionDefaultParams")
    public void testInlineFunctionDefaultParams() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionDefaultParams/");
    }

    @Test
    @TestMetadata("inlineFunctionWithObject")
    public void testInlineFunctionWithObject() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/inlineFunctionWithObject/");
    }

    @Test
    @TestMetadata("interfaceOpenMethods")
    public void testInterfaceOpenMethods() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/interfaceOpenMethods/");
    }

    @Test
    @TestMetadata("interfaceOpenMethodsInOpenClass")
    public void testInterfaceOpenMethodsInOpenClass() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/interfaceOpenMethodsInOpenClass/");
    }

    @Test
    @TestMetadata("interfaceSuperUsage")
    public void testInterfaceSuperUsage() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/interfaceSuperUsage/");
    }

    @Test
    @TestMetadata("interfaceWithDefaultParams")
    public void testInterfaceWithDefaultParams() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/interfaceWithDefaultParams/");
    }

    @Test
    @TestMetadata("jsCode")
    public void testJsCode() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/jsCode/");
    }

    @Test
    @TestMetadata("jsCodeWithConstString")
    public void testJsCodeWithConstString() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/jsCodeWithConstString/");
    }

    @Test
    @TestMetadata("jsExport")
    public void testJsExport() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/jsExport/");
    }

    @Test
    @TestMetadata("jsModuleAnnotation")
    public void testJsModuleAnnotation() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/jsModuleAnnotation/");
    }

    @Test
    @TestMetadata("languageVersionSettings")
    public void testLanguageVersionSettings() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/languageVersionSettings/");
    }

    @Test
    @TestMetadata("localInlineFunction")
    public void testLocalInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/localInlineFunction/");
    }

    @Test
    @TestMetadata("localObjectsLeakThroughInterface")
    public void testLocalObjectsLeakThroughInterface() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/localObjectsLeakThroughInterface/");
    }

    @Test
    @TestMetadata("mainModuleInkonstidation")
    public void testMainModuleInkonstidation() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/mainModuleInkonstidation/");
    }

    @Test
    @TestMetadata("moveAndModifyInlineFunction")
    public void testMoveAndModifyInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/moveAndModifyInlineFunction/");
    }

    @Test
    @TestMetadata("moveExternalDeclarationsBetweenJsModules")
    public void testMoveExternalDeclarationsBetweenJsModules() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/moveExternalDeclarationsBetweenJsModules/");
    }

    @Test
    @TestMetadata("moveFilesBetweenModules")
    public void testMoveFilesBetweenModules() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/moveFilesBetweenModules/");
    }

    @Test
    @TestMetadata("moveInlineFunctionBetweenModules")
    public void testMoveInlineFunctionBetweenModules() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/moveInlineFunctionBetweenModules/");
    }

    @Test
    @TestMetadata("nestedClass")
    public void testNestedClass() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/nestedClass/");
    }

    @Test
    @TestMetadata("nonInlineBecomeInline")
    public void testNonInlineBecomeInline() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/nonInlineBecomeInline/");
    }

    @Test
    @TestMetadata("privateDeclarationLeakThroughDefaultParam")
    public void testPrivateDeclarationLeakThroughDefaultParam() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/privateDeclarationLeakThroughDefaultParam/");
    }

    @Test
    @TestMetadata("privateInlineFunction1")
    public void testPrivateInlineFunction1() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/privateInlineFunction1/");
    }

    @Test
    @TestMetadata("privateObjectsLeakThroughSealedInterface")
    public void testPrivateObjectsLeakThroughSealedInterface() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/privateObjectsLeakThroughSealedInterface/");
    }

    @Test
    @TestMetadata("removeFile")
    public void testRemoveFile() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/removeFile/");
    }

    @Test
    @TestMetadata("removeModule")
    public void testRemoveModule() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/removeModule/");
    }

    @Test
    @TestMetadata("removeUnusedFile")
    public void testRemoveUnusedFile() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/removeUnusedFile/");
    }

    @Test
    @TestMetadata("renameFile")
    public void testRenameFile() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/renameFile/");
    }

    @Test
    @TestMetadata("renameModule")
    public void testRenameModule() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/renameModule/");
    }

    @Test
    @TestMetadata("simple")
    public void testSimple() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/simple/");
    }

    @Test
    @TestMetadata("splitJoinModule")
    public void testSplitJoinModule() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/splitJoinModule/");
    }

    @Test
    @TestMetadata("suspendFunctions")
    public void testSuspendFunctions() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/suspendFunctions/");
    }

    @Test
    @TestMetadata("suspendInterfaceWithDefaultParams")
    public void testSuspendInterfaceWithDefaultParams() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/suspendInterfaceWithDefaultParams/");
    }

    @Test
    @TestMetadata("toplevelProperties")
    public void testToplevelProperties() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/toplevelProperties/");
    }

    @Test
    @TestMetadata("transitiveInlineFunction")
    public void testTransitiveInlineFunction() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/transitiveInlineFunction/");
    }

    @Test
    @TestMetadata("typeScriptExports")
    public void testTypeScriptExports() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/typeScriptExports/");
    }

    @Test
    @TestMetadata("unicodeSerializationAndDeserialization")
    public void testUnicodeSerializationAndDeserialization() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/unicodeSerializationAndDeserialization/");
    }

    @Test
    @TestMetadata("updateExports")
    public void testUpdateExports() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/updateExports/");
    }

    @Test
    @TestMetadata("updateExportsAndInlineImports")
    public void testUpdateExportsAndInlineImports() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/updateExportsAndInlineImports/");
    }

    @Test
    @TestMetadata("variance")
    public void testVariance() throws Exception {
        runTest("js/js.translator/testData/incremental/inkonstidation/variance/");
    }
}
