// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst uintProgression = 1u..7u
        for (i in uintProgression step -1) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst ulongProgression = 1uL..7uL
        for (i in ulongProgression step -1L) {
        }
    }

    return "OK"
}