/*
 * KOTLIN CODEGEN BOX SPEC TEST (POSITIVE)
 *
 * SPEC VERSION: 0.1-300
 * MAIN LINK: expressions, constant-literals, boolean-literals -> paragraph 1 -> sentence 2
 * NUMBER: 21
 * DESCRIPTION: The use of Boolean literals as the identifier (with backtick) in the catchBlock.
 * NOTE: this test data is generated by FeatureInteractionTestDataGenerator. DO NOT MODIFY CODE MANUALLY!
 */

annotation class A

fun box(): String? {
    var konstue_1 = false
    var konstue_2 = true

    try {
        throw Exception()
    } catch (`true`: Throwable) {
        konstue_1 = true
    }

    try {
        throw Exception()
    } catch (@A `false`: Throwable) {
        konstue_2 = false
    }

    if (!konstue_1 || konstue_2) return null

    return "OK"
}