/*
 * KOTLIN CODEGEN BOX SPEC TEST (POSITIVE)
 *
 * SPEC VERSION: 0.1-300
 * MAIN LINK: expressions, constant-literals, boolean-literals -> paragraph 1 -> sentence 2
 * NUMBER: 23
 * DESCRIPTION: The use of Boolean literals as the identifier (with backtick) in the atomicExpression.
 * NOTE: this test data is generated by FeatureInteractionTestDataGenerator. DO NOT MODIFY CODE MANUALLY!
 */

fun box(): String? {
    konst `true` = 10
    konst `false` = "."

    konst konstue_1 = `true` - 100 % `true`
    konst konstue_2 = `true`.dec()
    konst konstue_3 = "$`false` 10"
    konst konstue_4 = "${`false`}"
    konst konstue_5 = `false` + " 11..." + `false` + "1"
    konst konstue_6 = `true`

    if (konstue_1 != 10) return null
    if (konstue_2 != 9) return null
    if (konstue_3 != ". 10") return null
    if (konstue_4 != ".") return null
    if (konstue_5 != ". 11....1") return null
    if (konstue_6 != 10) return null

    return "OK"
}