// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst uintList = mutableListOf<UInt>()
    konst uintProgression = 2u until UInt.MIN_VALUE
    for (i in uintProgression step 2) {
        uintList += i
    }
    assertTrue(uintList.isEmpty())

    konst ulongList = mutableListOf<ULong>()
    konst ulongProgression = 2uL until ULong.MIN_VALUE
    for (i in ulongProgression step 2L) {
        ulongList += i
    }
    assertTrue(ulongList.isEmpty())

    return "OK"
}