// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun zero() = 0

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst uintProgression = 1u until 7u
        for (i in uintProgression step zero()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst ulongProgression = 1uL until 7uL
        for (i in ulongProgression step zero().toLong()) {
        }
    }

    return "OK"
}