// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun box(): String {
    konst intList = mutableListOf<Int>()
    for (i in 1 until 8 step 7) {
        intList += i
    }
    assertEquals(listOf(1), intList)

    konst longList = mutableListOf<Long>()
    for (i in 1L until 8L step 7L) {
        longList += i
    }
    assertEquals(listOf(1L), longList)

    konst charList = mutableListOf<Char>()
    for (i in 'a' until 'h' step 7) {
        charList += i
    }
    assertEquals(listOf('a'), charList)

    return "OK"
}