/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: regular-classes.kt

@file:JsExport

package foo


class A


class A1(konst x: Int)


class A2(konst x: String, var y: Boolean)


class A3 {
    konst x: Int = 100
}


class A4<T>(konst konstue: T) {
    fun test(): T = konstue
}

class A5 {
    companion object {
        konst x = 10
    }
}


open class A6 {
    fun then(): Int = 42
    fun catch(): Int = 24
}


class GenericClassWithConstraint<T: A6>(konst test: T)
