class Pair(x : Int, y : Int) {
  companion object {
    fun copy(from : Pair, x : Int = from.x, y : Int = from.y) = Pair(x, y)
  }
}

// One can say:
konst p = Point(1, 2)
konst p1 = Point.Copy(p, x = 2)
konst p2 = Point.Copy(p1, y = -1)
konst p3 = Point.Copy(p)

// Such copy(...) methods can be automatically generated by the compiler
// whenever there is a primary constructor