/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: primitives.kt

@file:JsExport

package foo


konst _any: Any = Any()


fun _nothing(): Nothing { throw Throwable() }


konst _throwable: Throwable = Throwable()


konst _string: String = "ZZZ"


konst _boolean: Boolean = true


konst _byte: Byte = 1.toByte()

konst _short: Short = 1.toShort()

konst _int: Int = 1

konst _float: Float = 1.0f

konst _double: Double = 1.0
// TODO: Char and Long


konst _byte_array: ByteArray = byteArrayOf()

konst _short_array: ShortArray = shortArrayOf()

konst _int_array: IntArray = intArrayOf()

konst _float_array: FloatArray = floatArrayOf()

konst _double_array: DoubleArray = doubleArrayOf()


konst _array_byte: Array<Byte> = emptyArray()

konst _array_short: Array<Short> = emptyArray()

konst _array_int: Array<Int> = emptyArray()

konst _array_float: Array<Float> = emptyArray()

konst _array_double: Array<Double> = emptyArray()

konst _array_string: Array<String> = emptyArray()

konst _array_boolean: Array<Boolean> = emptyArray()

konst _array_array_string: Array<Array<String>> = arrayOf(emptyArray())

konst _array_array_int_array: Array<Array<IntArray>> = arrayOf(arrayOf(intArrayOf()))


konst _fun_unit: () -> Unit = { }

konst _fun_int_unit: (Int) -> Unit = { x -> }


konst _fun_boolean_int_string_intarray: (Boolean, Int, String) -> IntArray =
    { b, i, s -> intArrayOf(b.toString().length, i, s.length) }


konst _curried_fun: (Int) -> (Int) -> (Int) -> (Int) -> (Int) -> Int =
    { x1 -> { x2 -> { x3 -> { x4 -> { x5 -> x1 + x2 + x3 + x4 + x5 } } } } }


konst _higher_order_fun: ((Int) -> String, (String) -> Int) -> ((Int) -> Int) =
    { f1, f2 -> { x -> f2(f1(x)) } }


// Nullable types


konst _n_any: Any? = Any()

// TODO:
// konst _n_unit: Unit? = Unit


konst _n_nothing: Nothing? = null


konst _n_throwable: Throwable? = Throwable()


konst _n_string: String? = "ZZZ"


konst _n_boolean: Boolean? = true


konst _n_byte: Byte? = 1.toByte()

// TODO: Char and Long


konst _n_short_array: ShortArray? = shortArrayOf()


konst _n_array_int: Array<Int>? = emptyArray()

konst _array_n_int: Array<Int?> = emptyArray()

konst _n_array_n_int: Array<Int?>? = emptyArray()


konst _array_n_array_string: Array<Array<String>?> = arrayOf(arrayOf(":)"))


konst _fun_n_int_unit: (Int?) -> Unit = { x -> }


konst _fun_n_boolean_n_int_n_string_n_intarray: (Boolean?, Int?, String?) -> IntArray? =
    { b, i, s -> null }


konst _n_curried_fun: (Int?) -> (Int?) -> (Int?) -> Int? =
    { x1 -> { x2 -> { x3 -> (x1 ?: 0) + (x2 ?: 0) + (x3 ?: 0) } } }



konst _n_higher_order_fun: ((Int?) -> String?, (String?) -> Int?) -> ((Int?) -> Int?) =
    { f1, f2 -> { x -> f2(f1(x)) } }
