// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf enum {@code org.jetbrains.kotlin.backend.common.serialization.proto.IrSyntheticBodyKind}
 */
public enum IrSyntheticBodyKind
    implements org.jetbrains.kotlin.protobuf.Internal.EnumLite {
  /**
   * <code>ENUM_VALUES = 1;</code>
   */
  ENUM_VALUES(0, 1),
  /**
   * <code>ENUM_VALUEOF = 2;</code>
   */
  ENUM_VALUEOF(1, 2),
  /**
   * <code>ENUM_ENTRIES = 3;</code>
   */
  ENUM_ENTRIES(2, 3),
  ;

  /**
   * <code>ENUM_VALUES = 1;</code>
   */
  public static final int ENUM_VALUES_VALUE = 1;
  /**
   * <code>ENUM_VALUEOF = 2;</code>
   */
  public static final int ENUM_VALUEOF_VALUE = 2;
  /**
   * <code>ENUM_ENTRIES = 3;</code>
   */
  public static final int ENUM_ENTRIES_VALUE = 3;


  public final int getNumber() { return konstue; }

  public static IrSyntheticBodyKind konstueOf(int konstue) {
    switch (konstue) {
      case 1: return ENUM_VALUES;
      case 2: return ENUM_VALUEOF;
      case 3: return ENUM_ENTRIES;
      default: return null;
    }
  }

  public static org.jetbrains.kotlin.protobuf.Internal.EnumLiteMap<IrSyntheticBodyKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static org.jetbrains.kotlin.protobuf.Internal.EnumLiteMap<IrSyntheticBodyKind>
      internalValueMap =
        new org.jetbrains.kotlin.protobuf.Internal.EnumLiteMap<IrSyntheticBodyKind>() {
          public IrSyntheticBodyKind findValueByNumber(int number) {
            return IrSyntheticBodyKind.konstueOf(number);
          }
        };

  private final int konstue;

  private IrSyntheticBodyKind(int index, int konstue) {
    this.konstue = konstue;
  }

  // @@protoc_insertion_point(enum_scope:org.jetbrains.kotlin.backend.common.serialization.proto.IrSyntheticBodyKind)
}
