// Auto-generated by GenerateSteppedRangesCodegenTestData. Do not edit!
// WITH_STDLIB
import kotlin.test.*

fun zero() = 0

fun box(): String {
    assertFailsWith<IllegalArgumentException> {
        konst uintProgression = 7u downTo 1u
        for (i in uintProgression step zero()) {
        }
    }

    assertFailsWith<IllegalArgumentException> {
        konst ulongProgression = 7uL downTo 1uL
        for (i in ulongProgression step zero().toLong()) {
        }
    }

    return "OK"
}