// SKIP_SIGNATURE_DUMP
// ^ Difference in annotations generated by K1 and K2

annotation class Ann

interface IFoo {
    @Ann konst testVal: String
    @Ann fun testFun()
    @Ann konst String.testExtVal: String
    @Ann fun String.testExtFun()
}

class DFoo(d: IFoo) : IFoo by d
