// SKIP_KT_DUMP
// TARGET_BACKEND: JVM

// SKIP_SIGNATURE_DUMP
// ^ Different types in annotations generated by K1 and K2

// FILE: A.java

public class A {
    @Annos(konstue = @Anno(token = "OK"))
    @Strings(konstue = "OK")
    @Ints(konstue = 42)
    @Enums(konstue = E.EA)
    @Classes(konstue = double.class)
    public void test() {}
}

// FILE: C.kt

import kotlin.reflect.KClass

annotation class Anno(konst token: String)
enum class E { EA }

annotation class Annos(konst konstue: Array<Anno>)
annotation class Strings(konst konstue: Array<String>)
annotation class Ints(konst konstue: IntArray)
annotation class Enums(konst konstue: Array<E>)
annotation class Classes(konst konstue: Array<KClass<*>>)

class C : A()
