package org.jetbrains.kotlin.gradle.targets.native.tasks.artifact

import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.KotlinArtifact
import org.jetbrains.kotlin.gradle.dsl.KotlinArtifactConfig
import org.jetbrains.kotlin.gradle.dsl.KotlinArtifactsExtension
import org.jetbrains.kotlin.gradle.plugin.mpp.BitcodeEmbeddingMode
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType
import org.jetbrains.kotlin.konan.target.DEPRECATED_TARGET_MESSAGE
import org.jetbrains.kotlin.konan.target.KonanTarget
import javax.inject.Inject

// DO NOT EDIT MANUALLY! Generated by org.jetbrains.kotlin.generators.gradle.dsl.KotlinArtifactsDSLCodegenKt

abstract class KotlinArtifactsExtensionImpl @Inject constructor(project: Project) : KotlinArtifactsExtension {

    override konst artifactConfigs = project.objects.domainObjectSet(KotlinArtifactConfig::class.java)
    override konst artifacts = project.objects.namedDomainObjectSet(KotlinArtifact::class.java)
    override konst Native = project.objects.newInstance(KotlinNativeArtifactDSLImpl::class.java, project)

    konst RELEASE = NativeBuildType.RELEASE
    konst DEBUG = NativeBuildType.DEBUG

    class BitcodeEmbeddingModeDsl {
        konst DISABLE = BitcodeEmbeddingMode.DISABLE
        konst BITCODE = BitcodeEmbeddingMode.BITCODE
        konst MARKER = BitcodeEmbeddingMode.MARKER
    }

    @JvmField
    konst EmbedBitcodeMode = BitcodeEmbeddingModeDsl()

    konst androidX64 = KonanTarget.ANDROID_X64
    konst androidX86 = KonanTarget.ANDROID_X86
    konst androidArm32 = KonanTarget.ANDROID_ARM32
    konst androidArm64 = KonanTarget.ANDROID_ARM64
    konst iosArm64 = KonanTarget.IOS_ARM64
    konst iosX64 = KonanTarget.IOS_X64
    konst iosSimulatorArm64 = KonanTarget.IOS_SIMULATOR_ARM64
    konst watchosArm32 = KonanTarget.WATCHOS_ARM32
    konst watchosArm64 = KonanTarget.WATCHOS_ARM64
    konst watchosX64 = KonanTarget.WATCHOS_X64
    konst watchosSimulatorArm64 = KonanTarget.WATCHOS_SIMULATOR_ARM64
    konst watchosDeviceArm64 = KonanTarget.WATCHOS_DEVICE_ARM64
    konst tvosArm64 = KonanTarget.TVOS_ARM64
    konst tvosX64 = KonanTarget.TVOS_X64
    konst tvosSimulatorArm64 = KonanTarget.TVOS_SIMULATOR_ARM64
    konst linuxX64 = KonanTarget.LINUX_X64
    konst mingwX64 = KonanTarget.MINGW_X64
    konst macosX64 = KonanTarget.MACOS_X64
    konst macosArm64 = KonanTarget.MACOS_ARM64
    konst linuxArm64 = KonanTarget.LINUX_ARM64


    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst iosArm32 = KonanTarget.IOS_ARM32

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst watchosX86 = KonanTarget.WATCHOS_X86

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst mingwX86 = KonanTarget.MINGW_X86

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst linuxArm32Hfp = KonanTarget.LINUX_ARM32_HFP

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst linuxMips32 = KonanTarget.LINUX_MIPS32

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst linuxMipsel32 = KonanTarget.LINUX_MIPSEL32

    @Deprecated(DEPRECATED_TARGET_MESSAGE, level = DeprecationLevel.ERROR)
    konst wasm32 = KonanTarget.WASM32

}