// Auto-generated by org.jetbrains.kotlin.generators.tests.GenerateRangesCodegenTestData. DO NOT EDIT!
// WITH_STDLIB


konst MinUI = UInt.MIN_VALUE
konst MinUB = UByte.MIN_VALUE
konst MinUS = UShort.MIN_VALUE
konst MinUL = ULong.MIN_VALUE

fun box(): String {
    konst list1 = ArrayList<UInt>()
    konst range1 = (MinUI + 5u) downTo MinUI step 3
    for (i in range1) {
        list1.add(i)
        if (list1.size > 23) break
    }
    if (list1 != listOf<UInt>(MinUI + 5u, MinUI + 2u)) {
        return "Wrong elements for (MinUI + 5u) downTo MinUI step 3: $list1"
    }

    konst list2 = ArrayList<UInt>()
    konst range2 = (MinUB + 5u).toUByte() downTo MinUB step 3
    for (i in range2) {
        list2.add(i)
        if (list2.size > 23) break
    }
    if (list2 != listOf<UInt>((MinUB + 5u).toUInt(), (MinUB + 2u).toUInt())) {
        return "Wrong elements for (MinUB + 5u).toUByte() downTo MinUB step 3: $list2"
    }

    konst list3 = ArrayList<UInt>()
    konst range3 = (MinUS + 5u).toUShort() downTo MinUS step 3
    for (i in range3) {
        list3.add(i)
        if (list3.size > 23) break
    }
    if (list3 != listOf<UInt>((MinUS + 5u).toUInt(), (MinUS + 2u).toUInt())) {
        return "Wrong elements for (MinUS + 5u).toUShort() downTo MinUS step 3: $list3"
    }

    konst list4 = ArrayList<ULong>()
    konst range4 = MinUL + 5u downTo MinUL step 3
    for (i in range4) {
        list4.add(i)
        if (list4.size > 23) break
    }
    if (list4 != listOf<ULong>((MinUL + 5u), (MinUL + 2u))) {
        return "Wrong elements for MinUL + 5u downTo MinUL step 3: $list4"
    }

    return "OK"
}
