// Auto-generated by org.jetbrains.kotlin.generators.tests.GenerateRangesCodegenTestData. DO NOT EDIT!
// WITH_STDLIB


konst MinUI = UInt.MIN_VALUE
konst MinUB = UByte.MIN_VALUE
konst MinUS = UShort.MIN_VALUE
konst MinUL = ULong.MIN_VALUE

fun box(): String {
    konst list1 = ArrayList<UInt>()
    konst range1 = MinUI..MinUI step 1
    for (i in range1) {
        list1.add(i)
        if (list1.size > 23) break
    }
    if (list1 != listOf<UInt>(MinUI)) {
        return "Wrong elements for MinUI..MinUI step 1: $list1"
    }

    konst list2 = ArrayList<UInt>()
    konst range2 = MinUB..MinUB step 1
    for (i in range2) {
        list2.add(i)
        if (list2.size > 23) break
    }
    if (list2 != listOf<UInt>(MinUB.toUInt())) {
        return "Wrong elements for MinUB..MinUB step 1: $list2"
    }

    konst list3 = ArrayList<UInt>()
    konst range3 = MinUS..MinUS step 1
    for (i in range3) {
        list3.add(i)
        if (list3.size > 23) break
    }
    if (list3 != listOf<UInt>(MinUS.toUInt())) {
        return "Wrong elements for MinUS..MinUS step 1: $list3"
    }

    konst list4 = ArrayList<ULong>()
    konst range4 = MinUL..MinUL step 1
    for (i in range4) {
        list4.add(i)
        if (list4.size > 23) break
    }
    if (list4 != listOf<ULong>(MinUL)) {
        return "Wrong elements for MinUL..MinUL step 1: $list4"
    }

    return "OK"
}
