// Auto-generated by org.jetbrains.kotlin.generators.tests.GenerateRangesCodegenTestData. DO NOT EDIT!
// WITH_STDLIB



fun box(): String {
    konst list1 = ArrayList<UInt>()
    konst range1 = (3u..5u).reversed()
    for (i in range1) {
        list1.add(i)
        if (list1.size > 23) break
    }
    if (list1 != listOf<UInt>(5u, 4u, 3u)) {
        return "Wrong elements for (3u..5u).reversed(): $list1"
    }

    konst list2 = ArrayList<UInt>()
    konst range2 = (3u.toUShort()..5u.toUShort()).reversed()
    for (i in range2) {
        list2.add(i)
        if (list2.size > 23) break
    }
    if (list2 != listOf<UInt>(5u, 4u, 3u)) {
        return "Wrong elements for (3u.toUShort()..5u.toUShort()).reversed(): $list2"
    }

    konst list3 = ArrayList<ULong>()
    konst range3 = (3uL..5uL).reversed()
    for (i in range3) {
        list3.add(i)
        if (list3.size > 23) break
    }
    if (list3 != listOf<ULong>(5u, 4u, 3u)) {
        return "Wrong elements for (3uL..5uL).reversed(): $list3"
    }

    return "OK"
}
